### ISSUE TITLE
Not really an issue: Upload to OPAR

### ISSUE THREAD

**Issue by reneeb** [carlosfrodriguez/CRDashboardKPIs#1]
Hi Carlos,

I'd like to ask if you would upload your add on to OPAR (http://opar.perl-services.de). This add on looks interesting...

Kind regards,
Renée

**Comment by carlosfrodriguez** [comment]
Hi @reneeb,

Thanks for your proposal, but I should not do that. Thanks again.

((enjoy))
cr
