### ISSUE TITLE
Uppercase Folder

### ISSUE THREAD

**Issue by joserribeiro26** [carlosfrodriguez/CRDashboardKPIs#2]
Carlos,

O Folders name is in uppercase, to work I need do this.

ln -s justGage.1.0.1 JustGage.1.0.1
ln -s codemirror.4.3 Codemirror.4.3

**Comment by trakinasman** [comment]
carlos good day , did the process of allocation of files on the KPI , raised the module in the admin guide, and I disabled the loader module js .
when I enter the KPI tab in the Admin module , I get the error "Internal Server Error " , had any release or permission to be considered for release access to KPI guide ?
